// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'delete-confirm'
  | 'delete-success'
  | 'error-select-one-mapped'
  | 'menu-delete-document'
  | 'menu-open-document'
  | 'menu-root'
  | 'menu-sync-collection'
  | 'menu-sync-selected'
  | 'pref-app-id'
  | 'pref-app-secret'
  | 'pref-authorize'
  | 'pref-help'
  | 'pref-logout'
  | 'pref-redirect-uri'
  | 'pref-target-folder'
  | 'pref-test'
  | 'pref-title'
  | 'sync-no-items'
  | 'sync-starting';
